<?php
/**
 * Assamese Extended Knowledge Base — 28 entries
 * School ERP PHP v3.0
 * Ported from assameseExtendedKnowledge.js (Node.js reference implementation)
 *
 * Each entry: id, title, tags[], content, language
 * Used by api/chatbot/chat.php → searchExtendedKB()
 */

return [
    [
        'id'       => 'as-greeting',
        'title'    => 'EduGlass সহায়ক পৰিচয়',
        'tags'     => ['নমস্কাৰ', 'সহায়', 'মদত', 'চৈটবট', 'বট', 'hello', 'hi', 'help'],
        'content'  => "নমস্কাৰ। মই EduGlass School ERP সহায়ক। আপুনি মোৰ ওচৰত ছাত্ৰ ভৰ্তি, উপস্থিতি, মাছুল, পৰীক্ষা, পুস্তকালয়, হোষ্টেল, পৰিবহণ, অভিযোগ, নোটিছ, গৃহকাৰ্য, ৰুটিন আৰু দৰমহাৰ বিষয়ে সহায় বিচাৰিব পাৰে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-admission-process',
        'title'    => 'ছাত্ৰ ভৰ্তি প্ৰক্ৰিয়া',
        'tags'     => ['ভৰ্তি', 'ছাত্ৰক কেনেকৈ ভৰ্তি', 'ভৰ্তি প্ৰক্ৰিয়া', 'admission', 'নতুন ছাত্ৰ'],
        'content'  => "নতুন ছাত্ৰক ভৰ্তি কৰিবলৈ Students Page লৈ যাওক। Admit Student বুটামত ক্লিক কৰক। নাম, জন্ম তাৰিখ, লিংগ, শ্ৰেণী, বিভাগ, অভিভাৱকৰ তথ্য আৰু নথি আপল'ড কৰি ফৰ্ম জমা দিয়ক।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-admission-documents',
        'title'    => 'ভৰ্তিৰ বাবে প্ৰয়োজনীয় নথি',
        'tags'     => ['ভৰ্তি নথি', 'documents', 'জন্ম প্ৰমাণপত্ৰ', 'tc', 'transfer certificate'],
        'content'  => "সাধাৰণতে ভৰ্তিৰ বাবে জন্ম প্ৰমাণপত্ৰ, TC, পাছপৰ্ট ফটো, পূৰ্বৰ শিক্ষাগত নথি আৰু প্ৰয়োজন হলে স্থানীয় পৰিচয়পত্ৰ লোৱা হয়। বিদ্যালয়ৰ নীতি অনুসৰি নথিৰ তালিকা সামান্য ভিন্ন হ'ব পাৰে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-student-profile',
        'title'    => 'ছাত্ৰৰ প্ৰফাইল আৰু ৰেকৰ্ড',
        'tags'     => ['ছাত্ৰ প্ৰফাইল', 'student profile', 'ছাত্ৰৰ তথ্য', 'record'],
        'content'  => "ছাত্ৰৰ প্ৰফাইলত সাধাৰণতে নাম, ৰ'ল নম্বৰ, ভৰ্তি নম্বৰ, শ্ৰেণী, বিভাগ, অভিভাৱকৰ যোগাযোগ, জন্ম তাৰিখ, ঠিকনা আৰু নথিপত্ৰ সংৰক্ষিত থাকে। এই তথ্য আপডেট কৰোঁতে সচেতন হ'ব লাগিব কাৰণ বহু মডিউল এই ডাটাৰ ওপৰত নিৰ্ভৰ কৰে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-attendance-marking',
        'title'    => 'উপস্থিতি চিহ্নিত কৰাৰ ধাপ',
        'tags'     => ['উপস্থিতি', 'চিহ্নিত', 'mark attendance', 'আজিৰ উপস্থিতি', 'attendance'],
        'content'  => "Attendance Page খুলি শ্ৰেণী আৰু তাৰিখ বাছক। প্ৰতিজন ছাত্ৰক উপস্থিত, অনুপস্থিত, পলম বা আধা-দিন হিচাপে চিহ্নিত কৰক। তাৰ পিছত Save Attendance ক্লিক কৰক।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-attendance-report',
        'title'    => 'উপস্থিতি প্ৰতিবেদন',
        'tags'     => ['উপস্থিতি প্ৰতিবেদন', 'attendance report', 'মাহিলী উপস্থিতি', 'defaulter'],
        'content'  => "উপস্থিতি প্ৰতিবেদনত দৈনিক, মাহিলী, শ্ৰেণীভিত্তিক আৰু কম উপস্থিতি থকা ছাত্ৰৰ তালিকা পোৱা যায়। পৰীক্ষাৰ যোগ্যতাৰ বাবে নূন্যতম উপস্থিতি শতকৰা হাৰ মনত ৰাখিব লাগে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-leave-balance',
        'title'    => 'ছুটি আৰু জেৰ',
        'tags'     => ['ছুটি', 'leave balance', 'sick leave', 'casual leave', 'earned leave'],
        'content'  => "কৰ্মচাৰীৰ ক্ষেত্ৰত casual leave, sick leave আৰু earned leave ধৰণৰ ছুটি থাকিব পাৰে। Leave module ত balance, approved আবেদন আৰু pending আবেদন দেখা যায়।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-fee-collection',
        'title'    => 'মাছুল সংগ্ৰহ',
        'tags'     => ['মাছুল', 'fee collection', 'ৰচিদ', 'payment', 'fee'],
        'content'  => "Fee Page লৈ গৈ Collect Fee ক্লিক কৰক। ছাত্ৰ বাছি fee head, amount আৰু payment mode পূৰণ কৰক। Save কৰাৰ পিছত receipt তৈয়াৰ হয়।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-fee-modes',
        'title'    => 'পৰিশোধৰ ধৰণ',
        'tags'     => ['payment mode', 'নগদ', 'upi', 'card', 'cheque', 'bank transfer'],
        'content'  => "মাছুল পৰিশোধৰ সাধাৰণ ধৰণসমূহ হ'ল নগদ, কাৰ্ড, UPI, cheque আৰু bank transfer। কোন payment mode ব্যৱহাৰ হৈছে সেয়া entry সময়ত ঠিককৈ বাছিব লাগিব।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-fee-due',
        'title'    => 'বাকী মাছুল আৰু defaulter',
        'tags'     => ['মাছুল বাকী', 'due fee', 'defaulter', 'pending fee'],
        'content'  => "যি ছাত্ৰৰ মাছুল নিৰ্ধাৰিত তাৰিখৰ ভিতৰত পৰিশোধ নহয়, সিহঁত defaulter তালিকাত দেখাব পাৰে। Collection report আৰু student fee history চাই বাকী মাছুল ধৰা যায়।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-exam-schedule',
        'title'    => 'পৰীক্ষাৰ সময়সূচী',
        'tags'     => ['পৰীক্ষা', 'schedule exam', 'পৰীক্ষাৰ সময়সূচী', 'exam schedule'],
        'content'  => "Exams module ত শ্ৰেণী, বিষয়, তাৰিখ, সময়, total marks আৰু passing marks দি পৰীক্ষা schedule কৰিব পাৰি। পৰীক্ষা entry কৰাৰ পিছত timetable আৰু result workflow আৰম্ভ হয়।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-exam-results',
        'title'    => 'ফলাফল আৰু report card',
        'tags'     => ['ফলাফল', 'marks entry', 'report card', 'grade', 'result'],
        'content'  => "Marks entry শেষ হলে grade calculation আৰু report card generation কৰিব পাৰি। Student-wise result, subject-wise analysis আৰু PDF report card Exams module ত উপলব্ধ।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-homework',
        'title'    => 'গৃহকাৰ্য ব্যৱস্থাপনা',
        'tags'     => ['গৃহকাৰ্য', 'assignment', 'homework', 'pending homework'],
        'content'  => "Homework module ত শিক্ষকসকলে class-wise homework post কৰিব পাৰে। ছাত্ৰ বা অভিভাৱকে pending homework, due date আৰু instruction চাব পাৰে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-routine',
        'title'    => 'শ্ৰেণী ৰুটিন',
        'tags'     => ['ৰুটিন', 'timetable', 'class routine', 'আজিৰ ৰুটিন', 'routine'],
        'content'  => "Routine module ত class routine, subject timing আৰু period-wise schedule সংৰক্ষণ হয়। শিক্ষক বা ছাত্ৰে শ্ৰেণীভিত্তিক সময়সূচী চাব পাৰে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-library-issue',
        'title'    => 'কিতাপ issue কৰাৰ ধাপ',
        'tags'     => ['পুস্তকালয়', 'কিতাপ issue', 'book issue', 'library', 'issue book', 'কিতাপ কেনেকৈ issue'],
        'content'  => "Library module খুলি catalog ত কিতাপ বাছক। Issue option ত গৈ ছাত্ৰ, due date আৰু remarks পূৰণ কৰক। Issued transaction history পাছত track কৰিব পাৰি।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-library-return',
        'title'    => 'কিতাপ return আৰু fine',
        'tags'     => ['কিতাপ return', 'fine', 'overdue', 'library fine'],
        'content'  => "Overdue কিতাপ return কৰাৰ সময় system এ late fine calculate কৰিব পাৰে। Return কৰাৰ সময় remarks আৰু final status update কৰিব লাগে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-canteen-menu',
        'title'    => 'কেণ্টিন মেনু আৰু wallet',
        'tags'     => ['কেণ্টিন', 'মেনু', 'food', 'lunch menu', 'wallet', 'canteen'],
        'content'  => "Canteen module ত উপলব্ধ food items, price আৰু quantity দেখা যায়। Student wallet balance check, recharge আৰু quick billing একে module ৰ অংশ।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-canteen-wallet',
        'title'    => 'কেণ্টিন wallet recharge',
        'tags'     => ['wallet balance', 'recharge', 'rfid', 'কেণ্টিন ৱালেট'],
        'content'  => "Student wallet ত balance কম থাকিলে recharge entry কৰিব পাৰি। RFID বা wallet-based payment কেণ্টিন sales workflow ৰ সৈতে সংযুক্ত থাকিব পাৰে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-hostel-allocation',
        'title'    => 'হোষ্টেল room allocation',
        'tags'     => ['হোষ্টেল', 'room allot', 'allocation', 'bed', 'hostel room'],
        'content'  => "Hostel module ত room type, room number আৰু bed capacity define কৰা হয়। তাৰ পিছত student allotment কৰি room allocate কৰিব পাৰি।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-hostel-rules',
        'title'    => 'হোষ্টেল নিয়ম',
        'tags'     => ['হোষ্টেল নিয়ম', 'warden', 'curfew', 'visitor'],
        'content'  => "Hostel stay ৰ ক্ষেত্ৰত visitor timing, warden approval, curfew timing আৰু room discipline মানি চলিব লাগে। Vacate process শেষ নকৰালৈ room occupied দেখুৱাই থাকিব পাৰে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-transport-routes',
        'title'    => 'পৰিবহণ route ব্যৱস্থাপনা',
        'tags'     => ['পৰিবহণ', 'bus route', 'driver', 'conductor', 'transport'],
        'content'  => "Transport module ত vehicle, route, driver আৰু conductor assign কৰা হয়। Student assignment সম্পূৰ্ণ হ'লে bus-wise attendance বা trip data manage কৰিব পাৰি।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-transport-attendance',
        'title'    => 'বাস attendance',
        'tags'     => ['bus attendance', 'boarded', 'dropped', 'বাস উপস্থিতি'],
        'content'  => "Driver বা conductor role ৰ user এ assigned bus ৰ বাবে boarded, dropped বা absent status update কৰিব পাৰে। Transport attendance parent alert flow ৰ সৈতে জড়িত থাকিব পাৰে।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-payroll',
        'title'    => 'Payroll আৰু payslip',
        'tags'     => ['দৰমহা', 'salary', 'payroll', 'payslip', 'pay'],
        'content'  => "Payroll module ত salary batch generate, paid status mark আৰু payslip view কৰিব পাৰি। Staff account ৰ বাবে latest salary record আৰু deductions দেখা যায়।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-notices',
        'title'    => 'নোটিছ আৰু announcement',
        'tags'     => ['নোটিছ', 'announcement', 'notice board', 'জাননী', 'notice'],
        'content'  => "Notices module ত বিদ্যালয়ৰ জাননী, ঘোষণা, important updates আৰু role-based notice distribution দেখা যায়। Recent notices dashboard বা notices page ত পোৱা যায়।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-complaints',
        'title'    => 'অভিযোগ দাখিল',
        'tags'     => ['অভিযোগ', 'complaint', 'grievance'],
        'content'  => "Complaints module ত issue type, priority আৰু description দি complaint submit কৰিব পাৰি। Complaint status, assignee আৰু resolution note পাছত track কৰিব পাৰি।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-dashboard',
        'title'    => "ডেশ্বব'ৰ্ড overview",
        'tags'     => ["ডেশ্বব'ৰ্ড", 'dashboard', 'stats', 'overview', 'summary'],
        'content'  => "Dashboard ত students count, attendance summary, fees collection, notices আৰু role-specific quick actions দেখা যায়। ব্যৱহাৰকাৰীৰ role অনুসৰি তথ্য সলনি হয়।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-password-guidance',
        'title'    => 'লগইন আৰু password সহায়',
        'tags'     => ['password reset', 'login problem', 'sign in', 'প্ৰৱেশ', 'password'],
        'content'  => "লগইন সমস্যা হলে system administrator বা authorized staff ৰ সহায় ল'ব লাগে। Shared default password ৰ ওপৰত নিৰ্ভৰ নকৰি user-specific reset workflow ব্যৱহাৰ কৰাটো সুৰক্ষিত।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-parent-help',
        'title'    => 'অভিভাৱকৰ বাবে সহায়',
        'tags'     => ['অভিভাৱক', 'parent', 'child fee', 'child attendance'],
        'content'  => "অভিভাৱকে linked child ৰ attendance, fee history, result, homework আৰু notices চাব পাৰিব। Data scope linked student records ৰ ভিতৰত সীমাবদ্ধ থকাটো সুৰক্ষাৰ বাবে জৰুৰী।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-student-help',
        'title'    => 'ছাত্ৰৰ self-service সহায়',
        'tags'     => ['ছাত্ৰ সহায়', 'my attendance', 'my fee', 'my exam', 'student help'],
        'content'  => "ছাত্ৰে নিজৰ উপস্থিতি, নিজৰ মাছুল স্থিতি, upcoming exams, ফলাফল, homework আৰু library issue history বিচাৰিব পাৰে। অন্য user ৰ data দেখা নাপায়।",
        'language' => 'as',
    ],
    [
        'id'       => 'as-teacher-help',
        'title'    => 'শিক্ষকৰ বাবে সহায়',
        'tags'     => ['শিক্ষক', 'teacher help', 'class summary', 'marks entry'],
        'content'  => "শিক্ষকে class-wise attendance mark, homework publish, marks entry, notices বা remarks manage কৰিব পাৰে। Data access assigned class বা অনুমোদিত scope ৰ ভিতৰত থাকিব লাগে।",
        'language' => 'as',
    ],

    // ── PORTED FROM Node.js curatedKnowledgeBase.json (Assamese) ──────

    ['id' => 'as-scholarship', 'title' => 'বৃত্তিৰ তথ্য', 'tags' => ['বৃত্তি', 'scholarship', 'আৰ্থিক সহায়', 'financial aid', 'concession'], 'content' => 'মেধাৱী আৰু আৰ্থিকভাৱে দুৰ্বল ছাত্ৰৰ বাবে বৃত্তি উপলব্ধ। আবেদন জুন-জুলাইত গ্ৰহণ কৰা হয়। মানদণ্ড: ৮০%+ নম্বৰ, পৰিয়ালৰ আয় ₹২ লাখ/বছৰৰ তলত। বৃত্তি ৫০-১০০% টিউচন মাচুল কভাৰ কৰে।', 'language' => 'as'],
    ['id' => 'as-bus-timing', 'title' => 'বাছৰ ৰুট আৰু সময়ৰ তথ্য', 'tags' => ['বাছ', 'bus route', 'পৰিবহণ', 'timing', 'GPS', 'pickup', 'drop'], 'content' => 'বিদ্যালয়ৰ ১৫টা বাছ ৰুট আছে। Pickup: ৭:০০-৭:৪৫ AM, Drop: ৩:১৫-৪:০০ PM। GPS ট্ৰেকিং parent app ত উপলব্ধ। ৰুট সলনিৰ বাবে ১৫ দিন আগতে আবেদন কৰক। মাচুল: ₹১,৫০০-৩,০০০/মাহ।', 'language' => 'as'],
    ['id' => 'as-calendar', 'title' => 'বিদ্যালয়ৰ কেলেণ্ডাৰ আৰু বন্ধ ২০২৫-২৬', 'tags' => ['কেলেণ্ডাৰ', 'calendar', 'বন্ধ', 'holiday', 'vacation', 'বিহু', 'Diwali'], 'content' => 'বিদ্যালয় সোমবাৰ-শনিবাৰ (৮ AM - ৩ PM)। প্ৰধান বন্ধ: প্ৰজাতন্ত্ৰ দিৱস (২৬ জান), স্বাধীনতা দিৱস (১৫ আগ), বিহু (১৪-১৫ এপ্রিল), দুৰ্গাপূজা (অক্ট ২০-২৪), দীপাৱলী (নভ ১), বৰদিন (ডিছ ২৫)। গ্রীষ্মকালীন বন্ধ: ১৫ এপ্ৰিল - ৩১ মে।', 'language' => 'as'],
    ['id' => 'as-hostel-curfew', 'title' => 'হোষ্টেলৰ নিয়ম আৰু Curfew সময়', 'tags' => ['curfew', 'hostel', 'study hours', 'mess', 'হোষ্টেল নিয়ম'], 'content' => 'Curfew: ৮ PM (Junior), ৯ PM (Senior)। Mess সময়: জলপান ৭-৮ AM, মধ্যাহ্ন ভোজন ১২:৩০-১:৩০ PM, ৰাতিৰ আহাৰ ৭-৮ PM। অধ্যয়ন সময়: ৭-৯ PM (বাধ্যতামূলক)। সপ্তাহান্তত বাহিৰ যাবলৈ অভিভাৱকৰ অনুমতি লাগে।', 'language' => 'as'],
    ['id' => 'as-attendance-75', 'title' => 'উপস্থিতিৰ নূন্যতম প্রয়োজনীয়তা', 'tags' => ['উপস্থিতি', '75%', 'minimum attendance', 'promotion', 'detention'], 'content' => 'পৰৱৰ্তী শ্ৰেণীলৈ উন্নীত হ'বলৈ নূন্যতম ৭৫% উপস্থিতি প্ৰয়োজন। ৭৫%ৰ তলৰ ছাত্ৰক শৈক্ষণিক সমিতিৰ সন্মুখত হাজিৰ হ'ব লাগিব। ৭০% আৰু ৬৫%ত অভিভাৱকক জনোৱা হয়।', 'language' => 'as'],
    ['id' => 'as-exam-hall', 'title' => 'পৰীক্ষা হলৰ নিয়ম', 'tags' => ['পৰীক্ষা নিয়ম', 'exam hall', 'malpractice', 'invigilator', 'devices'], 'content' => 'পৰীক্ষা আৰম্ভৰ ৩০ মিনিট আগতে উপস্থিত হওক। পৰিচয়পত্ৰ অবশ্যই আনক। ইলেকট্রনিক ডিভাইচ নিষিদ্ধ (ফোন, smartwatch)। কেৱল ক\'লা/নীলা কলম ব্যৱহাৰ কৰক। অসদাচৰণত অযোগ্য ঘোষণা আৰু অভিভাৱকক মতা হ\'ব।', 'language' => 'as'],
    ['id' => 'as-fee-refund', 'title' => 'মাচুল ঘূৰাই দিয়াৰ নীতি', 'tags' => ['refund', 'fee return', 'withdrawal', 'মাচুল ঘূৰাই'], 'content' => 'মাচুল ঘূৰাই দিয়া কেৱল প্ৰত্যাহাৰৰ ৩০ দিনৰ ভিতৰত সম্ভৱ। ভৰ্তি, উন্নয়ন আৰু বাৰ্ষিক মাচুল non-refundable। ১৫ কাৰ্যদিনৰ ভিতৰত বেংক একাউণ্টত জমা হয়। লিখিত আবেদন অধ্যক্ষলৈ দিব লাগিব।', 'language' => 'as'],
    ['id' => 'as-fee-installment', 'title' => 'মাচুল কিস্তিৰ বিকল্প', 'tags' => ['installment', 'কিস্তি', 'monthly fee', 'discount', 'EWS', 'concession'], 'content' => 'মাচুল কিস্তি বিকল্প: বাৰ্ষিক (৫% ছাড়), আধা-বাৰ্ষিক (২ কিস্তি), ত্রৈমাসিক (৪ কিস্তি), মাহিলী (২% surcharge)। Grace period ১৫ দিন। EWS (₹১.৫L ৰ তলৰ আয়) ৰ বাবে concession উপলব্ধ।', 'language' => 'as'],
    ['id' => 'as-parent-portal', 'title' => 'অভিভাৱক পৰ্টেল আৰু সুবিধা', 'tags' => ['parent portal', 'app', 'login', 'android', 'iOS', 'features', 'অভিভাৱক পৰ্টেল'], 'content' => 'Parent portal ত: উপস্থিতি ট্ৰেকিং, মাচুল পৰিশোধ, পৰীক্ষাৰ ফলাফল, গৃহকাৰ্য, শিক্ষকৰ বার্তা, বাছ GPS, নোটিচ ব\'ৰ্ড। Android/iOS app উপলব্ধ। সহায়: parentportal@school.edu বা ext. 101।', 'language' => 'as'],
    ['id' => 'as-counseling', 'title' => 'শিক্ষাৰ্থী পৰামৰ্শ সেৱা', 'tags' => ['counseling', 'পৰামৰ্শ', 'mental health', 'stress', 'career', 'counselor'], 'content' => 'বিনামূলীয়া পৰামৰ্শ সেৱা উপলব্ধ। পৰামৰ্শদাতা সোমবাৰ-শুক্ৰবাৰ (৯ AM - ৪ PM)। গোপনীয় অধিবেশন। সেৱা: শৈক্ষণিক মানসিক চাপ, জীৱিকা নিৰ্দেশনা, ব্যক্তিগত সমস্যা, পৰীক্ষাৰ উদ্বেগ।', 'language' => 'as'],
    ['id' => 'as-lab-safety', 'title' => 'পৰীক্ষাগাৰ সুৰক্ষা নিয়ম', 'tags' => ['lab', 'laboratory', 'safety', 'science lab', 'computer lab', 'rules', 'পৰীক্ষাগাৰ'], 'content' => 'বিজ্ঞান আৰু কম্পিউটাৰ llab ত lab coat পৰিধান বাধ্যতামূলক। খোৱা-বোৱা নিষিদ্ধ। শিক্ষকৰ নিৰ্দেশ মানক। সৰঞ্জাম নষ্ট হ\'লে তৎক্ষণাৎ জনাওক। প্ৰতিটো lab ত first aid kit।', 'language' => 'as'],
    ['id' => 'as-career', 'title' => 'জীৱিকা নিৰ্দেশনা আৰু কলেজ প্ৰস্তুতি', 'tags' => ['career', 'college', 'aptitude', 'stream', 'entrance', 'guidance', 'জীৱিকা'], 'content' => 'Class 9 ৰ পৰা জীৱিকা পৰামৰ্শ আৰম্ভ হয়। সেৱা: aptitude test (Class 9, 11), College guidance (Class 12), বৃত্তি সন্ধান, Entrance exam টিপছ, বাৰ্ষিক career fair। Class 10 ৰ ফলাফলৰ পিছত stream বাছনি।', 'language' => 'as'],
    ['id' => 'as-lost-found', 'title' => 'হেৰোৱা-পোৱা প্ৰক্ৰিয়া', 'tags' => ['lost', 'found', 'হেৰোৱা', 'পোৱা', 'lost and found', 'belongings'], 'content' => 'হেৰোৱা বস্তু বিদ্যালয় কাৰ্যালয়ত জনাওক। পোৱা বস্তু ৩০ দিন ৰখা হয়। মোবাইল, মানিবেগ আদি মূল্যৱান বস্তু office safe ত সুৰক্ষিত। ৩০ দিনৰ পিছত দান কৰা হয়।', 'language' => 'as'],
    ['id' => 'as-security', 'title' => 'বিদ্যালয়ৰ সুৰক্ষা আৰু CCTV', 'tags' => ['CCTV', 'security', 'safety', 'guard', 'evacuation', 'fire', 'সুৰক্ষা'], 'content' => '২৪/৭ CCTV পৰ্যবেক্ষণ। সকলো গেটত নিৰাপত্তাৰক্ষী। পৰিচয়পত্ৰ প্ৰৱেশৰ বাবে বাধ্যতামূলক। প্ৰতি ত্ৰৈমাসিকত আপদকালীন অনুশীলন। প্ৰতিটো মজিয়াত অগ্নিনিৰ্বাপক যন্ত্ৰ। Emergency: Security ext. 999।', 'language' => 'as'],
    ['id' => 'as-academic-year', 'title' => 'শৈক্ষণিক বৰ্ষৰ গঠন', 'tags' => ['academic year', 'term', 'school term', 'report card', 'শৈক্ষণিক বৰ্ষ'], 'content' => 'শৈক্ষণিক বৰ্ষ: এপ্ৰিলৰ পৰা মাৰ্চ। ৪টা term: Term 1 (এপ্ৰ-জুন), Term 2 (জুল-ছেপ), Term 3 (অক্ট-ডিছ), Term 4 (জান-মাৰ)। প্ৰতিটো termৰ পিছত report card। Term 2 আৰু Term 4 ৰ ফলাফলৰ পিছত PTM।', 'language' => 'as'],
    
    // NEWLY ADDED POLICY PARITY
    ['id' => 'as-anti-bullying', 'title' => 'এণ্টি-বুলিং নীতি', 'tags' => ['bullying', 'ragging', 'anti-bullying', 'বুলিং', 'ৰেগিং', 'report', 'অভিযোগ'], 'content' => 'বিদ্যালয়ত বুলিংৰ বাবে শূণ্য সহনশীলতা আছে। যিকোনো ৰূপত (শारीरिक, মৌখিক বা চাইবাৰ) বুলিং কৰিলে কঠোৰ অনুশাসনামূলক ব্যৱস্থা গ্ৰহণ কৰা হ\'ব। ছাত্ৰ-ছাত্ৰীয়ে লগে লগে শিক্ষকক অভিযোগ কৰিব পাৰে। নামহীন অভিযোগ গ্ৰহণযোগ্য।', 'language' => 'as'],
    ['id' => 'as-uniform', 'title' => 'বিদ্যালয়ৰ ইউনিফৰ্ম নীতি', 'tags' => ['uniform', 'dress code', 'pants', 'shirt', 'ইউনিফৰ্ম', 'পোছাক', 'সাজপাৰ'], 'content' => 'বিদ্যালয়ৰ ইউনিফৰ্ম পৰিধান কৰা বাধ্যতামূলক। গ্ৰীষ্মকাল: পাতল নীলা ছাৰ্ট/চালোৱাৰ আৰু ডাঠ নীলা পেণ্ট/স্কাৰ্ট। শীতকাল: ছাই ৰঙৰ চুইটাৰ। পি.টি.ৰ দিনা স্পোৰ্টছ ইউনিফৰ্ম। ক\'লা জোতা আৰু নেম বেজ পৰিধান কৰিব লাগিব।', 'language' => 'as'],
    ['id' => 'as-mobile', 'title' => 'মবাইল ফোন নীতি', 'tags' => ['mobile', 'phone', 'smartwatch', 'মবাইল', 'ফোন', 'device', 'gadget'], 'content' => 'শ্ৰেণী চলি থকা সময়ত মবাইল ফোন ব্যৱহাৰ নিষেধ। ফোন চুইচ অফ কৰি বেগত ৰাখিব লাগে। জৰুৰী কলৰ বাবে অফিচ ব্যৱহাৰ কৰিব পাৰে। জব্দ কৰা ফোন কেৱল অভিভাৱকক ঘূৰাই দিয়া হ\'ব।', 'language' => 'as'],
    ['id' => 'as-late-coming', 'title' => 'পলমকৈ অহাৰ নীতি', 'tags' => ['late', 'arrival', 'time', 'পলম', 'punctual', 'penalty'], 'content' => '৮:১৫ AM ৰ পিছত অহা ছাত্ৰক পলম হোৱা (Late) বুলি ধৰা হ\'ব। তিনিবাৰ পলম কৰিলে এদিন অনুপস্থিত বুলি গণ্য কৰা হ\'ব। বাৰে বাৰে পলম কৰিলে অভিভাৱকক মাতি অনা হ\'ব। অফিচৰ পৰা লেট স্লিপ সংগ্ৰহ কৰাটো জৰুৰী।', 'language' => 'as'],
    ['id' => 'as-hw-grading', 'title' => 'গৃহকাৰ্য গ্ৰেডিং নীতি', 'tags' => ['homework', 'grading', 'marks', 'গৃহকাৰ্য', 'গ্ৰেড'], 'content' => 'গৃহকাৰ্যক ১০-পইণ্ট স্কেলত গ্ৰেডিং কৰা হয়। গ্ৰেড নিৰ্ভৰ কৰে সম্পূৰ্ণতা, শুদ্ধতা আৰু সময়ানুৱৰ্তিতাৰ ওপৰত। পলমকৈ জমা দিলে নম্বৰ কটা যাব পাৰে।', 'language' => 'as'],
    ['id' => 'as-lib-rules', 'title' => 'পুস্তকালয়ৰ নিয়ম', 'tags' => ['library', 'borrow', 'return', 'fine', 'পুস্তকালয়', 'কিতাপ'], 'content' => 'ছাত্ৰ-ছাত্ৰীয়ে ৭ দিনৰ বাবে ২খন কিতাপ নিব পাৰে। পলমকৈ ঘূৰাই দিলে প্ৰতিদিনে ₹৫ জৰিমনা ভৰিব লাগিব। কিতাপ হেৰালে বৰ্তমানৰ মূল্য পৰিশোধ কৰিব লাগিব। পৰীক্ষাৰ সময়ত কিতাপ দিয়া নহয়।', 'language' => 'as'],
];
