<?php
/**
 * Hindi Extended Knowledge Base — 28 entries
 * School ERP PHP v3.0
 * Ported from hindiExtendedKnowledge.js (Node.js reference implementation)
 *
 * Each entry: id, title, tags[], content, language
 * Used by api/chatbot/chat.php → searchExtendedKB()
 */

return [
    [
        'id'       => 'hi-greeting',
        'title'    => 'EduGlass सहायक परिचय',
        'tags'     => ['नमस्ते', 'हेलो', 'मदद', 'सहायता', 'बॉट', 'hello', 'hi', 'help'],
        'content'  => 'नमस्ते। मैं EduGlass School ERP सहायक हूं। मैं छात्र प्रवेश, उपस्थिति, फीस, परीक्षा, पुस्तकालय, छात्रावास, परिवहन, शिकायत, नोटिस, होमवर्क और पेरोल से जुड़ी सहायता दे सकता हूं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-admission-process',
        'title'    => 'छात्र प्रवेश प्रक्रिया',
        'tags'     => ['प्रवेश', 'भर्ती', 'admission', 'student admission', 'छात्र प्रवेश', 'नया छात्र'],
        'content'  => 'नए छात्र को जोड़ने के लिए Students page खोलें। Admit Student पर क्लिक करें। छात्र का नाम, जन्म तिथि, कक्षा, सेक्शन, अभिभावक की जानकारी और दस्तावेज़ भरकर फॉर्म submit करें।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-admission-documents',
        'title'    => 'प्रवेश के लिए आवश्यक दस्तावेज़',
        'tags'     => ['दस्तावेज़', 'documents', 'जन्म प्रमाण पत्र', 'tc', 'transfer certificate', 'birth certificate'],
        'content'  => 'प्रवेश के लिए सामान्यतः जन्म प्रमाण पत्र, TC, पासपोर्ट फोटो, पहचान पत्र और पिछली कक्षा के शैक्षणिक रिकॉर्ड की आवश्यकता होती है। विद्यालय की नीति के अनुसार सूची बदल सकती है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-student-profile',
        'title'    => 'छात्र प्रोफाइल और रिकॉर्ड',
        'tags'     => ['छात्र प्रोफाइल', 'student profile', 'student record', 'छात्र जानकारी', 'छात्र'],
        'content'  => 'छात्र प्रोफाइल में नाम, रोल नंबर, प्रवेश संख्या, कक्षा, सेक्शन, अभिभावक संपर्क, पता और आवश्यक दस्तावेज़ सुरक्षित रहते हैं। इन रिकॉर्ड को अपडेट करते समय सावधानी ज़रूरी है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-attendance-marking',
        'title'    => 'उपस्थिति दर्ज करने की प्रक्रिया',
        'tags'     => ['उपस्थिति', 'attendance', 'mark attendance', 'हाज़िरी', 'उपस्थिति दर्ज'],
        'content'  => 'Attendance page खोलें। कक्षा और तारीख चुनें। प्रत्येक छात्र को present, absent, late या half-day के रूप में चिह्नित करें। फिर Save Attendance पर क्लिक करें।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-attendance-report',
        'title'    => 'उपस्थिति रिपोर्ट',
        'tags'     => ['उपस्थिति रिपोर्ट', 'attendance report', 'मासिक उपस्थिति', 'defaulter', 'monthly attendance'],
        'content'  => 'उपस्थिति रिपोर्ट में दैनिक उपस्थिति, मासिक सारांश, कम उपस्थिति वाले छात्र और प्रतिशत आधारित summary शामिल हो सकते हैं। परीक्षा पात्रता के लिए न्यूनतम उपस्थिति ध्यान में रखें।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-leave-balance',
        'title'    => 'छुट्टी और leave balance',
        'tags'     => ['leave balance', 'छुट्टी', 'sick leave', 'casual leave', 'earned leave', 'छुट्टी बैलेंस'],
        'content'  => 'Staff accounts के लिए casual leave, sick leave और earned leave balance देखा जा सकता है। Leave module में approved, pending और rejected आवेदन भी दिखते हैं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-fee-collection',
        'title'    => 'फीस संग्रह प्रक्रिया',
        'tags'     => ['फीस', 'fee collection', 'payment', 'receipt', 'रसीद', 'फीस जमा'],
        'content'  => 'Fee page में Collect Fee चुनें। छात्र, fee head, राशि और payment mode दर्ज करें। Save करने के बाद receipt तैयार होती है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-fee-modes',
        'title'    => 'भुगतान के तरीके',
        'tags'     => ['payment mode', 'नकद', 'upi', 'card', 'cheque', 'bank transfer', 'भुगतान'],
        'content'  => 'सामान्य payment modes हैं: cash, card, UPI, cheque और bank transfer। Entry करते समय सही payment mode चुनना ज़रूरी है ताकि रिपोर्ट सही बने।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-fee-due',
        'title'    => 'बाकी फीस और defaulter',
        'tags'     => ['बाकी फीस', 'due fee', 'pending fee', 'defaulter', 'बकाया'],
        'content'  => 'जिन छात्रों की फीस समय पर जमा नहीं होती वे defaulter list में दिखाई दे सकते हैं। Collection report और student fee history से बाकी फीस की जांच की जा सकती है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-exam-schedule',
        'title'    => 'परीक्षा समय सारणी',
        'tags'     => ['परीक्षा', 'exam schedule', 'समय सारणी', 'schedule exam', 'timetable exam'],
        'content'  => 'Exams module में कक्षा, विषय, तारीख, समय, total marks और passing marks देकर परीक्षा schedule की जा सकती है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-exam-results',
        'title'    => 'परिणाम और report card',
        'tags'     => ['परिणाम', 'marks entry', 'report card', 'grade', 'result', 'ग्रेड'],
        'content'  => 'Marks entry पूरी होने के बाद grade calculation और report card generation किया जा सकता है। Student-wise result और subject analysis भी उपलब्ध हो सकते हैं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-homework',
        'title'    => 'होमवर्क प्रबंधन',
        'tags'     => ['होमवर्क', 'homework', 'assignment', 'गृहकार्य', 'pending homework'],
        'content'  => 'Homework module में शिक्षक class-wise homework publish कर सकते हैं। छात्र और अभिभावक due date, pending homework और instructions देख सकते हैं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-routine',
        'title'    => 'कक्षा रूटीन',
        'tags'     => ['रूटीन', 'timetable', 'समय सारणी', 'class routine', 'routine'],
        'content'  => 'Routine module में period-wise समय सारणी, subject schedule और class routine दिखाया जा सकता है। शिक्षक और छात्र दोनों इसका उपयोग कर सकते हैं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-library-issue',
        'title'    => 'किताब जारी करने के चरण',
        'tags'     => ['पुस्तकालय', 'library', 'book issue', 'किताब जारी', 'issue book', 'किताब'],
        'content'  => 'Library module खोलें। Catalog से किताब चुनें। Issue विकल्प में छात्र, due date और remarks भरें। बाद में transaction history से जारी की गई किताबें track की जा सकती हैं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-library-return',
        'title'    => 'किताब वापसी और fine',
        'tags'     => ['book return', 'fine', 'overdue', 'किताब वापसी', 'library fine'],
        'content'  => 'यदि किताब overdue है तो return करते समय system fine calculate कर सकता है। Return के बाद transaction status update करें।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-canteen-menu',
        'title'    => 'कैंटीन मेनू और wallet',
        'tags'     => ['कैंटीन', 'menu', 'food', 'lunch menu', 'wallet', 'canteen'],
        'content'  => 'Canteen module में उपलब्ध food items, price और quantity देखे जा सकते हैं। Student wallet balance, recharge और billing इसी module का हिस्सा हो सकते हैं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-canteen-wallet',
        'title'    => 'कैंटीन wallet recharge',
        'tags'     => ['wallet balance', 'recharge', 'rfid', 'कैंटीन वॉलेट', 'wallet recharge'],
        'content'  => 'Wallet balance कम होने पर recharge entry की जा सकती है। कुछ setups में RFID या wallet-based payment भी उपलब्ध होता है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-hostel-allocation',
        'title'    => 'छात्रावास room allocation',
        'tags'     => ['छात्रावास', 'hostel', 'room allot', 'allocation', 'bed', 'room allocation'],
        'content'  => 'Hostel module में room type, room number और bed capacity configure करें। उसके बाद student allotment के माध्यम से room allocate किया जा सकता है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-hostel-rules',
        'title'    => 'छात्रावास नियम',
        'tags'     => ['hostel rules', 'warden', 'curfew', 'visitor', 'छात्रावास नियम'],
        'content'  => 'Hostel stay के दौरान visitor timing, warden approval, curfew timing और room discipline का पालन करना चाहिए। Vacate process पूरा होने तक room occupied दिख सकता है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-transport-routes',
        'title'    => 'परिवहन route प्रबंधन',
        'tags'     => ['परिवहन', 'transport', 'bus route', 'driver', 'conductor', 'route'],
        'content'  => 'Transport module में vehicle, route, driver और conductor assign किए जाते हैं। Student assignment के बाद bus-wise attendance और route data manage किया जा सकता है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-transport-attendance',
        'title'    => 'बस attendance',
        'tags'     => ['bus attendance', 'boarded', 'dropped', 'बस उपस्थिति', 'transport attendance'],
        'content'  => 'Driver या conductor assigned bus के लिए boarded, dropped या absent status update कर सकते हैं। यह parent alert workflow से भी जुड़ सकता है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-payroll',
        'title'    => 'Payroll और payslip',
        'tags'     => ['पेरोल', 'salary', 'payroll', 'payslip', 'वेतन', 'salary slip'],
        'content'  => 'Payroll module में salary batch generate, paid status mark और payslip view किया जा सकता है। Staff account के लिए latest salary और deductions दिखाई दे सकते हैं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-notices',
        'title'    => 'नोटिस और announcement',
        'tags'     => ['नोटिस', 'notice', 'announcement', 'सूचना', 'circular'],
        'content'  => 'Notices module में स्कूल की घोषणाएं, महत्वपूर्ण अपडेट और role-based notices दिखाई देती हैं। Recent notices dashboard से भी उपलब्ध हो सकते हैं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-complaints',
        'title'    => 'शिकायत दर्ज करना',
        'tags'     => ['शिकायत', 'complaint', 'grievance', 'issue', 'शिकायत दर्ज'],
        'content'  => 'Complaints module में issue type, priority और description भरकर शिकायत submit की जा सकती है। बाद में complaint status और resolution note track किए जा सकते हैं।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-dashboard',
        'title'    => 'डैशबोर्ड overview',
        'tags'     => ['डैशबोर्ड', 'dashboard', 'stats', 'overview', 'summary'],
        'content'  => 'Dashboard में students count, attendance summary, fees collection, notices और role-specific quick actions दिखाई देते हैं। उपयोगकर्ता की role के अनुसार दृश्य बदल सकता है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-password-guidance',
        'title'    => 'लॉगिन और password सहायता',
        'tags'     => ['password reset', 'login problem', 'sign in', 'लॉगिन', 'password'],
        'content'  => 'यदि login में समस्या हो तो system administrator या authorized staff की मदद लें। Shared default password पर निर्भर रहने के बजाय user-specific reset workflow अधिक सुरक्षित है।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-parent-help',
        'title'    => 'अभिभावक सहायता',
        'tags'     => ['अभिभावक', 'parent', 'child fee', 'child attendance', 'parent help'],
        'content'  => 'अभिभावक linked child की attendance, fee history, result, homework और notices देख सकते हैं। Data access linked student records तक सीमित रहना चाहिए।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-student-help',
        'title'    => 'छात्र self-service सहायता',
        'tags'     => ['छात्र सहायता', 'my attendance', 'my fee', 'my exam', 'student help'],
        'content'  => 'छात्र अपनी attendance, fee status, upcoming exams, results, homework और library history देख सकता है। दूसरे उपयोगकर्ताओं का data उपलब्ध नहीं होना चाहिए।',
        'language' => 'hi',
    ],
    [
        'id'       => 'hi-teacher-help',
        'title'    => 'शिक्षक सहायता',
        'tags'     => ['शिक्षक', 'teacher help', 'class summary', 'marks entry', 'teacher'],
        'content'  => 'शिक्षक class-wise attendance mark, homework publish, marks entry, notices और remarks manage कर सकते हैं। Data access assigned class scope के भीतर रहना चाहिए।',
        'language' => 'hi',
    ],

    // ── PORTED FROM Node.js curatedKnowledgeBase.json (Hindi) ──────────

    ['id' => 'hi-scholarship', 'title' => 'छात्रवृत्ति जानकारी', 'tags' => ['छात्रवृत्ति', 'scholarship', 'वित्तीय सहायता', 'financial aid', 'concession'], 'content' => 'मेधावी और आर्थिक रूप से कमज़ोर छात्रों के लिए छात्रवृत्ति उपलब्ध है। आवेदन जून-जुलाई में स्वीकार किए जाते हैं। मानदंड: 80%+ अंक, परिवार की आय ₹2 लाख/वर्ष से कम। छात्रवृत्ति 50-100% ट्यूशन फीस कवर करती है।', 'language' => 'hi'],
    ['id' => 'hi-bus-timing', 'title' => 'बस रूट और समय जानकारी', 'tags' => ['बस', 'bus route', 'समय', 'timing', 'transport', 'GPS', 'pickup', 'drop'], 'content' => 'स्कूल के 15 बस रूट हैं। Pickup: 7:00-7:45 AM, Drop: 3:15-4:00 PM। GPS ट्रैकिंग parent app पर उपलब्ध। Route बदलने के लिए 15 दिन पहले आवेदन करें। फीस: ₹1,500-3,000/माह, दूरी के अनुसार।', 'language' => 'hi'],
    ['id' => 'hi-calendar', 'title' => 'स्कूल कैलेंडर और छुट्टियां 2025-26', 'tags' => ['कैलेंडर', 'calendar', 'छुट्टी', 'holiday', 'vacation', 'Diwali', 'summer break'], 'content' => 'स्कूल सोमवार-शनिवार (8 AM - 3 PM)। प्रमुख छुट्टियां: गणतंत्र दिवस (26 जन), स्वतंत्रता दिवस (15 अग), गांधी जयंती (2 अक्ट), दीपावली (1 नव), क्रिसमस (25 दिस)। ग्रीष्मकालीन अवकाश: 15 अप्रैल - 31 मई।', 'language' => 'hi'],
    ['id' => 'hi-hostel-curfew', 'title' => 'छात्रावास नियम और curfew समय', 'tags' => ['curfew', 'hostel timing', 'study hours', 'mess', 'छात्रावास'], 'content' => 'Curfew: 8 PM (जूनियर), 9 PM (सीनियर)। Mess टाइमिंग: नाश्ता 7-8 AM, लंच 12:30-1:30 PM, डिनर 7-8 PM। अध्ययन घंटे: 7-9 PM (अनिवार्य)। सप्ताहांत बाहर जाने के लिए माता-पिता की अनुमति ज़रूरी।', 'language' => 'hi'],
    ['id' => 'hi-attendance-75', 'title' => 'उपस्थिति न्यूनतम आवश्यकता', 'tags' => ['उपस्थिति', '75%', 'minimum attendance', 'promotion', 'detention', 'threshold'], 'content' => 'अगली कक्षा में पदोन्नति के लिए न्यूनतम 75% उपस्थिति आवश्यक है। 75% से कम उपस्थिति पर शैक्षणिक समिति के सामने पेश होना पड़ेगा। 70% और 65% पर माता-पिता को सूचित किया जाता है।', 'language' => 'hi'],
    ['id' => 'hi-exam-hall', 'title' => 'परीक्षा हॉल नियम', 'tags' => ['परीक्षा नियम', 'exam hall', 'malpractice', 'invigilator', 'devices'], 'content' => 'परीक्षा शुरू होने से 30 मिनट पहले उपस्थित हों। ID कार्ड अनिवार्य। इलेक्ट्रॉनिक उपकरण नहीं (फोन, smartwatch)। केवल काली/नीली पेन। कदाचार पर अयोग्यता और माता-पिता को बुलाया जाएगा।', 'language' => 'hi'],
    ['id' => 'hi-fee-refund', 'title' => 'फीस वापसी नीति', 'tags' => ['refund', 'fee return', 'withdrawal', 'वापसी', 'fee refund'], 'content' => 'फीस वापसी केवल withdrawal के 30 दिन के भीतर होती है। Admission, development और annual charges non-refundable हैं। Refund 15 कार्यदिवसों में बैंक में credit होती है। लिखित withdrawal आवेदन principal को देना होगा।', 'language' => 'hi'],
    ['id' => 'hi-fee-installment', 'title' => 'फीस किस्त विकल्प', 'tags' => ['installment', 'किस्त', 'monthly fee', 'discount', 'EWS', 'concession'], 'content' => 'फीस किस्त विकल्प: वार्षिक (5% छूट), अर्धवार्षिक (2 किस्त), त्रैमासिक (4 किस्त), मासिक (2% surcharge)। Grace period 15 दिन। EWS वर्ग (₹1.5L से कम आय) के लिए concession उपलब्ध।', 'language' => 'hi'],
    ['id' => 'hi-parent-portal', 'title' => 'अभिभावक पोर्टल और सुविधाएं', 'tags' => ['parent portal', 'app', 'login', 'android', 'iOS', 'features'], 'content' => 'Parent portal में: उपस्थिति tracking, फीस भुगतान, परीक्षा परिणाम, होमवर्क, शिक्षक संदेश, बस GPS, नोटिस बोर्ड। Android/iOS app उपलब्ध। Support: parentportal@school.edu या ext. 101।', 'language' => 'hi'],
    ['id' => 'hi-counseling', 'title' => 'छात्र परामर्श सेवाएं', 'tags' => ['counseling', 'परामर्श', 'mental health', 'stress', 'career guidance', 'counselor'], 'content' => 'निःशुल्क परामर्श सेवाएं उपलब्ध हैं। परामर्शदाता सोमवार-शुक्रवार (9 AM - 4 PM)। गोपनीय सत्र। सेवाएं: शैक्षणिक तनाव, करियर मार्गदर्शन, व्यक्तिगत समस्याएं, परीक्षा चिंता।', 'language' => 'hi'],
    ['id' => 'hi-lab-safety', 'title' => 'प्रयोगशाला सुरक्षा नियम', 'tags' => ['lab', 'laboratory', 'safety', 'science lab', 'computer lab', 'rules'], 'content' => 'विज्ञान और कंप्यूटर लैब में lab coat अनिवार्य। खाना-पीना नहीं। शिक्षक निर्देशों का पालन करें। उपकरण खराबी तुरंत रिपोर्ट करें। प्रत्येक लैब में first aid kit उपलब्ध।', 'language' => 'hi'],
    ['id' => 'hi-career', 'title' => 'करियर मार्गदर्शन', 'tags' => ['career', 'college', 'aptitude', 'stream selection', 'entrance exam', 'guidance'], 'content' => 'Class 9 से करियर परामर्श शुरू होता है। सेवाएं: aptitude test (Class 9, 11), College guidance (Class 12), Scholarship खोज, Entrance exam tips, वार्षिक career fair। Stream selection Class 10 के बाद।', 'language' => 'hi'],
    ['id' => 'hi-lost-found', 'title' => 'खोया-पाया प्रक्रिया', 'tags' => ['lost', 'found', 'खोया', 'पाया', 'lost and found', 'belongings'], 'content' => 'खोई वस्तु स्कूल कार्यालय को रिपोर्ट करें। मिली वस्तुएं 30 दिन रखी जाती हैं। मोबाइल, पर्स जैसी मूल्यवान चीज़ें office safe में सुरक्षित। 30 दिन बाद दान की जाती हैं।', 'language' => 'hi'],
    ['id' => 'hi-security', 'title' => 'स्कूल सुरक्षा और CCTV', 'tags' => ['CCTV', 'security', 'safety', 'guard', 'evacuation', 'fire', 'सुरक्षा'], 'content' => '24/7 CCTV निगरानी। सभी गेट पर सुरक्षा गार्ड। ID कार्ड प्रवेश के लिए अनिवार्य। त्रैमासिक आपदा अभ्यास। प्रत्येक मंजिल पर अग्निशामक यंत्र। Emergency: Security ext. 999।', 'language' => 'hi'],
    ['id' => 'hi-academic-year', 'title' => 'शैक्षणिक वर्ष संरचना', 'tags' => ['academic year', 'term', 'school term', 'report card', 'शैक्षणिक वर्ष'], 'content' => 'शैक्षणिक वर्ष: अप्रैल से मार्च। 4 semesters: Term 1 (अप्र-जून), Term 2 (जुल-सित), Term 3 (अक्ट-दिस), Term 4 (जन-मार)। प्रत्येक term के बाद report card। Term 2 और Term 4 के बाद PTM।', 'language' => 'hi'],
    
    // NEWLY ADDED POLICY PARITY
    ['id' => 'hi-anti-bullying', 'title' => 'एंटी-बुलिंग नीति', 'tags' => ['bullying', 'ragging', 'anti-bullying', 'बुलिंग', 'रैगिंग', 'report', 'शिकायत'], 'content' => 'स्कूल में बुलिंग के लिए जीरो टॉलरेंस है। किसी भी रूप (शारीरिक, मौखिक या साइबर) में बुलिंग पर कड़ी अनुशासनात्मक कार्रवाई होगी। कोई भी छात्र तुरंत किसी शिक्षक से शिकायत कर सकता है। गुमनाम शिकायतें भी स्वीकार की जाती हैं।', 'language' => 'hi'],
    ['id' => 'hi-uniform', 'title' => 'स्कूल यूनिफॉर्म नीति', 'tags' => ['uniform', 'dress code', 'pants', 'shirt', 'यूनिफॉर्म', 'वर्दी', 'पोशाक'], 'content' => 'स्कूल यूनिफॉर्म पहनना अनिवार्य है। गर्मी: हल्का नीला शर्ट/सलवार और गहरा नीला पैंट/स्कर्ट। सर्दी: ग्रे स्वेटर। खेल के दिन स्पोर्ट्स यूनिफॉर्म। काले जूते और नेम बैज हमेशा पहनना होगा।', 'language' => 'hi'],
    ['id' => 'hi-mobile', 'title' => 'मोबाइल फोन नीति', 'tags' => ['mobile', 'phone', 'smartwatch', 'मोबाइल', 'फोन', 'device', 'gadget'], 'content' => 'कक्षा के दौरान मोबाइल फोन वर्जित हैं। फोन को स्विच ऑफ करके बैग में रखना चाहिए। आपातकालीन कॉल ऑफिस से की जा सकती हैं। जब्त किए गए फोन केवल माता-पिता को लौटाए जाएंगे।', 'language' => 'hi'],
    ['id' => 'hi-late-coming', 'title' => 'देर से आने की नीति', 'tags' => ['late', 'arrival', 'time', 'देर', 'punctual', 'penalty'], 'content' => '8:15 AM के बाद आने वालों को देर से आया हुआ (Late) माना जाएगा। 3 बार देर से आने पर 1 अनुपस्थिति मानी जाएगी। बार-बार देर से आने पर माता-पिता को बुलाया जाएगा। ऑफिस से लेट स्लिप आवश्यक है।', 'language' => 'hi'],
    ['id' => 'hi-hw-grading', 'title' => 'होमवर्क ग्रेडिंग नीति', 'tags' => ['homework', 'grading', 'marks', 'होमवर्क', 'ग्रेड'], 'content' => 'होमवर्क 10-पॉइंट स्केल पर ग्रेड किया जाता है। ग्रेड होमवर्क की पूर्णता, सटीकता और समयबद्धता पर निर्भर करता है। देरी से जमा करने पर अंक काटे जा सकते हैं।', 'language' => 'hi'],
    ['id' => 'hi-lib-rules', 'title' => 'पुस्तकालय के नियम', 'tags' => ['library', 'borrow', 'return', 'fine', 'पुस्तकालय', 'किताब'], 'content' => 'छात्र 7 दिनों के लिए 2 किताबें ले सकते हैं। देरी से वापस करने पर ₹5 प्रतिदिन जुर्माना लगेगा। गुम होने पर किताब की पूरी कीमत देनी होगी। परीक्षा के दौरान किताबें जारी नहीं होतीं।', 'language' => 'hi'],
];
