<?php
/**
 * PDF Export API
 * School ERP PHP v3.0
 */

require_once __DIR__ . '/../../includes/db.php';
require_once __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/pdf_helpers.php';

require_auth();

$module = $_GET['module'] ?? '';
$dateFrom = $_GET['date_from'] ?? date('Y-m-01');
$dateTo = $_GET['date_to'] ?? date('Y-m-d');

switch ($module) {
    case 'students':
        export_students_pdf();
        break;
    case 'attendance':
        export_attendance_pdf($dateFrom, $dateTo);
        break;
    case 'fees':
        export_fees_pdf($dateFrom, $dateTo);
        break;
    case 'exams':
        export_exams_pdf();
        break;
    case 'library':
        export_library_pdf();
        break;
    case 'staff':
        export_staff_pdf();
        break;
    default:
        json_response(['error' => 'Invalid module. Use: students, attendance, fees, exams, library, staff'], 400);
}

function export_students_pdf()
{
    $parentPhoneExpr = db_column_exists('students', 'parent_phone') ? 's.parent_phone' : 's.phone';
    $rows = db_fetchAll(
        "SELECT s.admission_no, s.name, s.roll_number, s.dob, s.gender, s.parent_name,
                $parentPhoneExpr AS parent_phone, s.phone, s.email, c.name AS class_name
         FROM students s
         LEFT JOIN classes c ON s.class_id = c.id
         WHERE " . (db_column_exists('students', 'is_active') ? 's.is_active = 1' : '1=1') . "
         ORDER BY s.admission_no"
    );

    $tableRows = array_map(function ($row) {
        return [
            'Admission No' => $row['admission_no'],
            'Name' => $row['name'],
            'Class' => $row['class_name'] ?? '-',
            'DOB' => $row['dob'] ?: '-',
            'Gender' => ucfirst($row['gender'] ?? ''),
            'Parent' => $row['parent_name'] ?: '-',
            'Parent Phone' => $row['parent_phone'] ?: '-',
        ];
    }, $rows);

    audit_log('EXPORT', 'students', 'PDF export: ' . count($tableRows) . ' rows');
    pdf_output_sections(
        safe_download_filename('students', 'pdf'),
        'Students List',
        [pdf_table_section('Students', ['Admission No', 'Name', 'Class', 'DOB', 'Gender', 'Parent', 'Parent Phone'], $tableRows)],
        'Generated by ' . APP_NAME
    );
}

function export_attendance_pdf($dateFrom, $dateTo)
{
    $subjectExpr = db_column_exists('attendance', 'subject') ? 'a.subject' : "'-'";
    $rows = db_fetchAll(
        "SELECT a.date, a.status, a.note, $subjectExpr AS subject,
                s.name AS student_name, s.admission_no, c.name AS class_name
         FROM attendance a
         LEFT JOIN students s ON a.student_id = s.id
         LEFT JOIN classes c ON a.class_id = c.id
         WHERE a.date BETWEEN ? AND ?
         ORDER BY a.date DESC, s.name ASC",
        [$dateFrom, $dateTo]
    );

    $tableRows = array_map(function ($row) {
        return [
            'Date' => $row['date'],
            'Student' => $row['student_name'] ?? '-',
            'Admission No' => $row['admission_no'] ?? '-',
            'Class' => $row['class_name'] ?? '-',
            'Status' => ucfirst($row['status'] ?? ''),
            'Subject' => $row['subject'] ?: '-',
        ];
    }, $rows);

    audit_log('EXPORT', 'attendance', 'PDF export: ' . count($tableRows) . ' rows');
    pdf_output_sections(
        safe_download_filename('attendance', 'pdf'),
        'Attendance Report',
        [pdf_table_section('Attendance', ['Date', 'Student', 'Admission No', 'Class', 'Status', 'Subject'], $tableRows)],
        "Date range: {$dateFrom} to {$dateTo}"
    );
}

function export_fees_pdf($dateFrom, $dateTo)
{
    $discountExpr = db_column_exists('fees', 'discount') ? 'f.discount' : '0';
    $rows = db_fetchAll(
        "SELECT f.receipt_no, f.fee_type, f.total_amount, f.amount_paid, $discountExpr AS discount,
                f.balance_amount, f.payment_method, f.paid_date,
                s.name AS student_name, c.name AS class_name
         FROM fees f
         LEFT JOIN students s ON f.student_id = s.id
         LEFT JOIN classes c ON s.class_id = c.id
         WHERE f.paid_date BETWEEN ? AND ?
         ORDER BY f.paid_date DESC",
        [$dateFrom, $dateTo]
    );

    $tableRows = array_map(function ($row) {
        return [
            'Receipt No' => $row['receipt_no'] ?: '-',
            'Student' => $row['student_name'] ?: '-',
            'Class' => $row['class_name'] ?: '-',
            'Fee Type' => $row['fee_type'] ?: '-',
            'Paid' => pdf_money($row['amount_paid']),
            'Balance' => pdf_money($row['balance_amount']),
            'Date' => $row['paid_date'] ?: '-',
        ];
    }, $rows);

    audit_log('EXPORT', 'fees', 'PDF export: ' . count($tableRows) . ' rows');
    pdf_output_sections(
        safe_download_filename('fees', 'pdf'),
        'Fee Collection Report',
        [pdf_table_section('Fee Payments', ['Receipt No', 'Student', 'Class', 'Fee Type', 'Paid', 'Balance', 'Date'], $tableRows)],
        "Date range: {$dateFrom} to {$dateTo}"
    );
}

function export_exams_pdf()
{
    $rows = db_fetchAll(
        "SELECT e.name AS exam_name, e.subject, e.exam_date, e.max_marks,
                s.name AS student_name, s.admission_no, c.name AS class_name,
                er.marks_obtained, er.grade, er.status
         FROM exam_results er
         LEFT JOIN exams e ON er.exam_id = e.id
         LEFT JOIN students s ON er.student_id = s.id
         LEFT JOIN classes c ON e.class_id = c.id
         ORDER BY e.exam_date DESC, s.name ASC"
    );

    $tableRows = array_map(function ($row) {
        return [
            'Exam' => $row['exam_name'] ?: '-',
            'Subject' => $row['subject'] ?: '-',
            'Date' => $row['exam_date'] ?: '-',
            'Student' => $row['student_name'] ?: '-',
            'Class' => $row['class_name'] ?: '-',
            'Marks' => $row['marks_obtained'] ?? '-',
            'Status' => ucfirst($row['status'] ?? ''),
        ];
    }, $rows);

    audit_log('EXPORT', 'exams', 'PDF export: ' . count($tableRows) . ' rows');
    pdf_output_sections(
        safe_download_filename('exams', 'pdf'),
        'Exam Results',
        [pdf_table_section('Results', ['Exam', 'Subject', 'Date', 'Student', 'Class', 'Marks', 'Status'], $tableRows)],
        'Historical exam result export'
    );
}

function export_library_pdf()
{
    $rows = db_fetchAll(
        "SELECT b.title, b.author, b.isbn, b.category, b.total_copies, b.available_copies,
                li.issue_date, li.due_date, li.return_date, s.name AS student_name
         FROM library_books b
         LEFT JOIN library_issues li ON b.id = li.book_id
         LEFT JOIN students s ON li.student_id = s.id
         ORDER BY b.title ASC"
    );

    $tableRows = array_map(function ($row) {
        return [
            'Title' => $row['title'] ?: '-',
            'Author' => $row['author'] ?: '-',
            'ISBN' => $row['isbn'] ?: '-',
            'Category' => $row['category'] ?: '-',
            'Available' => ($row['available_copies'] ?? '-') . '/' . ($row['total_copies'] ?? '-'),
            'Issued To' => $row['student_name'] ?: '-',
        ];
    }, $rows);

    audit_log('EXPORT', 'library', 'PDF export: ' . count($tableRows) . ' rows');
    pdf_output_sections(
        safe_download_filename('library', 'pdf'),
        'Library Inventory',
        [pdf_table_section('Books and Issues', ['Title', 'Author', 'ISBN', 'Category', 'Available', 'Issued To'], $tableRows)],
        'Library stock and issue overview'
    );
}

function export_staff_pdf()
{
    $employeeExpr = db_column_exists('users', 'employee_id') ? 'u.employee_id' : 'NULL';
    $departmentExpr = db_column_exists('users', 'department') ? 'u.department' : "''";
    $designationExpr = db_column_exists('users', 'designation') ? 'u.designation' : "''";
    $phoneExpr = db_column_exists('users', 'phone') ? 'u.phone' : "''";
    $activeWhere = db_column_exists('users', 'is_active') ? 'AND u.is_active = 1' : '';

    $rows = db_fetchAll(
        "SELECT $employeeExpr AS employee_id, u.name, u.email, u.role,
                $departmentExpr AS department, $designationExpr AS designation, $phoneExpr AS phone
         FROM users u
         WHERE u.role NOT IN ('student', 'parent') $activeWhere
         ORDER BY u.name ASC"
    );

    $tableRows = array_map(function ($row) {
        return [
            'Employee ID' => $row['employee_id'] ?: '-',
            'Name' => $row['name'] ?: '-',
            'Email' => $row['email'] ?: '-',
            'Role' => role_label($row['role'] ?? ''),
            'Department' => $row['department'] ?: $row['designation'] ?: '-',
            'Phone' => $row['phone'] ?: '-',
        ];
    }, $rows);

    audit_log('EXPORT', 'staff', 'PDF export: ' . count($tableRows) . ' rows');
    pdf_output_sections(
        safe_download_filename('staff', 'pdf'),
        'Staff Directory',
        [pdf_table_section('Staff', ['Employee ID', 'Name', 'Email', 'Role', 'Department', 'Phone'], $tableRows)],
        'Active staff export'
    );
}
