@echo off
REM =====================================================
REM School ERP PHP v3.0 - Localhost Setup Script
REM For Windows (XAMPP/WAMP/Manual PHP Installation)
REM =====================================================

echo.
echo ====================================================
echo   School ERP PHP v3.0 - Localhost Deployment
echo ====================================================
echo.

REM Check if PHP is installed
where php >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [ERROR] PHP is not installed or not in PATH!
    echo.
    echo Please install PHP 7.4+ from:
    echo - XAMPP: https://www.apachefriends.org/
    echo - PHP Manual: https://windows.php.net/download/
    echo.
    pause
    exit /b 1
)

REM Check PHP version
php -v | findstr /C:"PHP 7" >nul
if %ERRORLEVEL% neq 0 (
    php -v | findstr /C:"PHP 8" >nul
    if %ERRORLEVEL% neq 0 (
        echo [ERROR] PHP 7.4+ or PHP 8.x required!
        pause
        exit /b 1
    )
)

echo [OK] PHP is installed
php -v | findstr /C:"PHP"
echo.

REM Check if MySQL is running
echo Checking MySQL...
mysql --version >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo [WARNING] MySQL client not found in PATH
    echo Assuming MySQL is running (check XAMPP/WAMP control panel)
    echo.
) else (
    echo [OK] MySQL is installed
    mysql --version
    echo.
)

REM Get project directory
SET PROJECT_DIR=%~dp0
echo Project Directory: %PROJECT_DIR%
echo.

REM Create .env.php for localhost
echo Creating localhost configuration...
(
echo ^<?php
echo // School ERP PHP - Localhost Configuration
echo // Auto-generated by setup_localhost.bat
echo.
echo // Database Configuration (XAMPP/WAMP defaults)
echo define^('DB_HOST', 'localhost'^);
echo define^('DB_NAME', 'school_erp'^);
echo define^('DB_USER', 'root'^);
echo define^('DB_PASS', ''^);
echo define^('DB_CHARSET', 'utf8mb4'^);
echo.
echo // Application
echo define^('APP_NAME', 'School ERP'^);
echo define^('APP_VERSION', '3.0'^);
echo define^('APP_ENV', 'development'^);
echo define^('APP_URL', 'http://localhost:8000'^);
echo define^('APP_DEBUG', 'true'^);
echo.
echo // Security (auto-generated)
echo define^('SESSION_SECRET', '%RANDOM%%RANDOM%%RANDOM%%RANDOM%' ^);
echo define^('CSRF_SECRET', '%RANDOM%%RANDOM%%RANDOM%%RANDOM%' ^);
echo define^('ENCRYPTION_KEY', '%RANDOM%%RANDOM%%RANDOM%%RANDOM%' ^);
echo.
echo // Session
echo define^('SESSION_LIFETIME', 28800^);
echo define^('SESSION_GC_MAXLIFETIME', 86400^);
echo define^('SESSION_COOKIE_SECURE', 'false'^);
echo define^('SESSION_COOKIE_HTTPONLY', 'true'^);
echo define^('SESSION_COOKIE_SAMESITE', 'Lax'^);
echo.
echo // Rate Limiting
echo define^('RATE_LIMIT_ENABLED', 'true'^);
echo define^('RATE_LIMIT_REQUESTS', 100^);
echo define^('RATE_LIMIT_WINDOW', 3600^);
echo define^('RATE_LIMIT_AUTH_REQUESTS', 10^);
echo define^('RATE_LIMIT_AUTH_WINDOW', 3600^);
echo.
echo // Account Lockout
echo define^('LOCKOUT_ENABLED', 'true'^);
echo define^('LOCKOUT_MAX_ATTEMPTS', 5^);
echo define^('LOCKOUT_DURATION', 900^);
echo.
echo // Password Reset
echo define^('RESET_TOKEN_EXPIRY', 3600^);
echo.
echo // File Upload
echo define^('UPLOAD_MAX_SIZE', 5242880^);
echo.
echo // SMS (Disabled for localhost)
echo define^('SMS_ENABLED', 'false'^);
echo.
echo // Email (Disabled for localhost)
echo define^('SMTP_HOST', ''^);
echo.
echo // AI Chatbot
echo define^('GEMINI_API_KEY', ''^);
echo.
echo // Pagination
echo define^('PAGINATION_DEFAULT', 20^);
echo define^('PAGINATION_MAX', 100^);
echo.
echo // Academic Year
echo define^('CURRENT_ACADEMIC_YEAR', '2025-2026'^);
echo.
echo // Timezone
echo date_default_timezone_set^('Asia/Kolkata'^);
echo.
echo // Error Reporting (Development Mode)
echo error_reporting^(-1^);
echo ini_set^('display_errors', 1^);
) > "%PROJECT_DIR%.env.php"

echo [OK] .env.php created for localhost
echo.

REM Create required directories
echo Creating required directories...
mkdir "%PROJECT_DIR%uploads" 2>nul
mkdir "%PROJECT_DIR%uploads\students" 2>nul
mkdir "%PROJECT_DIR%uploads\staff" 2>nul
mkdir "%PROJECT_DIR%uploads\books" 2>nul
mkdir "%PROJECT_DIR%tmp" 2>nul
mkdir "%PROJECT_DIR%tmp\cache" 2>nul
mkdir "%PROJECT_DIR%backups" 2>nul
mkdir "%PROJECT_DIR%logs" 2>nul

echo [OK] Directories created
echo.

REM Set directory permissions (Windows doesn't have chmod, skip this)
echo [SKIP] Directory permissions (Windows - not required)
echo.

REM Prompt for database setup
echo ====================================================
echo   DATABASE SETUP
echo ====================================================
echo.
echo This will create the 'school_erp' database and import the schema.
echo Make sure MySQL is running (check XAMPP/WAMP control panel).
echo.
set /p DB_SETUP="Do you want to setup the database now? (Y/N): "

if /i "%DB_SETUP%"=="Y" (
    echo.
    echo Creating database...
    mysql -u root -e "CREATE DATABASE IF NOT EXISTS school_erp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>nul
    if %ERRORLEVEL% neq 0 (
        echo [ERROR] Failed to create database. Is MySQL running?
        echo Please start MySQL from XAMPP/WAMP control panel and try again.
        echo.
        echo Manual setup:
        echo 1. Open phpMyAdmin: http://localhost/phpmyadmin
        echo 2. Create database: school_erp
        echo 3. Import: setup_complete.sql
        echo 4. Import: add_indexes.sql
    ) else (
        echo [OK] Database 'school_erp' created
        echo.
        
        echo Importing schema...
        mysql -u root school_erp < "%PROJECT_DIR%setup_complete.sql" 2>nul
        if %ERRORLEVEL% neq 0 (
            echo [WARNING] Schema import had issues (may already exist)
        ) else (
            echo [OK] Schema imported
        )
        echo.
        
        echo Adding performance indexes...
        mysql -u root school_erp < "%PROJECT_DIR%add_indexes.sql" 2>nul
        if %ERRORLEVEL% neq 0 (
            echo [WARNING] Index import had issues (may already exist)
        ) else (
            echo [OK] Indexes added
        )
        echo.
        
        echo [OK] Database setup complete!
    )
) else (
    echo.
    echo Skipping database setup.
    echo To setup manually:
    echo 1. Open phpMyAdmin: http://localhost/phpmyadmin
    echo 2. Create database: school_erp
    echo 3. Import: setup_complete.sql
    echo 4. Import: add_indexes.sql
)

echo.
echo ====================================================
echo   STARTING LOCAL SERVER
echo ====================================================
echo.
echo Starting PHP built-in server on http://localhost:8000
echo.
echo Server will run until you close this window.
echo Press Ctrl+C to stop the server.
echo.
echo ====================================================
echo.

REM Start PHP built-in server
cd /d "%PROJECT_DIR%"
start "School ERP - Local Server" http://localhost:8000
php -S localhost:8000 -t "%PROJECT_DIR%"

echo.
echo Server stopped.
pause
